import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import git from "../public/icons8-github-144.png"

import {useSession, signIn, signOut} from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const session = useSession()

  if (session.data === null) {
    return <Image onClick={signIn} src={git} width="0" height="0" alt=''/>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello {session?.data?.user?.name}</h1>

      <button onClick={signOut}>LogOut</button>
      
    </>
  )
}
